################
# DrupalCI GitLab CI configuration for Canvas Override
#
# @see https://www.drupal.org/drupalorg/docs/drupal-ci/customizing-drupalci-testing
################

################
# Includes
################
include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

################
# Variables
################
variables:
  OPT_IN_TEST_CURRENT: 1
  OPT_IN_TEST_NEXT_MAJOR: 0
  OPT_IN_TEST_NEXT_MINOR: 0
  OPT_IN_TEST_PREVIOUS_MAJOR: 0
  OPT_IN_TEST_PREVIOUS_MINOR: 0
  _TARGET_PHP: "8.3"
  SKIP_ESLINT: 1
  _PHPUNIT_EXTRA: --group canvas_override

################
# Build
################
composer:
  variables:
    COMPOSER_EXTRA_DEPENDENCIES: drupal/canvas:^1.2
  script:
    - composer config minimum-stability dev
    - composer config repositories.drupal composer https://packages.drupal.org/8
    - composer config --no-plugins allow-plugins.composer/installers true
    - composer config --no-plugins allow-plugins.cweagans/composer-patches true
    - composer config --no-plugins allow-plugins.oomphinc/composer-installers-extender true
    - composer config --no-plugins allow-plugins.phpstan/extension-installer true
    - composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
    - composer require --no-update cweagans/composer-patches:~1
    - |
      composer config extra.patches --json '{"drupal/canvas": {"feat: #3567225 Support per-entity Canvas layouts with field linking and template copying": "https://raw.githubusercontent.com/vardot/varbase-patches/refs/heads/patches/canvas--2026-04-02--3567225.patch"}}'
    - composer install -vvv

################
# Test
################
phpunit:
  parallel:
    matrix:
      - TESTSUITE:
        - kernel
        - functional-javascript
        - unit
